# make all the following files, in 'all'
# 'make all' to execute

sb: sb.cpp
	g++ sb.cpp -o sb
simplest: simplest.cpp
	g++ simplest.cpp -o simplest
123: 123.cpp
	g++ 123.cpp -o 123

all: simplest sb 123